---

- name: add defult directory if it does not exist
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: cd /mnt/c/Users/ksanc/Documents/work
    create: yes
  notify: source_bashrc


- name: add defult directory if it does not exist
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: "export PS1='\\[\\033[0;36m\\]\\u\\[\\033[0;32m\\]@\\h\\[\\033[1;30m\\]:\\w\\n\\[\\033[0m\\]$ '"
    create: yes
  notify: source_bashrc

- name: check mcfly
  stat:
    path: "/usr/local/bin/mcfly"
  register: mcfly_file

- name: Download mcfly installer
  get_url:
    url: https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh
    dest: /tmp/mcfly-installer.sh
  when: mcfly_file.stat.exists == false

- name: Execute the mcfly installer
  shell: cat /tmp/mcfly-installer.sh | sh -s  -- --git cantino/mcfly --force
  when: mcfly_file.stat.exists == false
  become: yes

- name: Remove the mcfly installer
  file:
    path: /tmp/mcfly-installer.sh
    state: absent
  when: mcfly_file.stat.exists == false

- name: add defult directory if it does not exist
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    line: 'eval "$(mcfly init bash)"'
    create: yes
  notify: source_bashrc

- name: add modern_commands
  apt:
    name: "{{ modern_commands }}"
    state: present
    update_cache: yes
  become: yes

- name: mkdir for bat
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    recurse: yes

- name: bat symbolic link to avoid a name clash with another package
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/bat"
    state: link
    mode: 755
  become: yes

- name: add util_commands
  apt:
    name: "{{ util_commands }}"
    state: present
    update_cache: yes
  become: yes
