---

- name: install python3-pip
  apt:
    name: python3-pip 
    state: present
    update_cache: yes
  become: yes
- name: intasll awscli
  pip:
    name: awscli
    state: latest
  become: yes
  
