---

- name: install nodejs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ nodejs_packages }}"
  become: yes

- name: install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  loop: "{{ npm_packages }}"
  notify: modify_bashrc
  become: yes
